filename: report_Adx_-_last_60_days_with_binary_clicks.csv
features:
    categorical:
        - account_id
        - geo_level_1
        - account_campaign:
                - account_id
                - campaign_id
        - account_banner:
                - account_id
                - banner_id
    continuous:
        - hx
        - hy
        - dx
        - dy
    label: clicks
    weight: impressions
